# Generated by Django 5.2.1 on 2025-05-25 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Module Name')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Module Code')),
                ('coordinating_instructor', models.CharField(max_length=100, verbose_name='Coordinating Instructor')),
                ('other_instructors', models.TextField(blank=True, verbose_name='Other Instructors')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('faculty', models.CharField(max_length=100, verbose_name='Faculty')),
                ('university', models.CharField(default='Vilnius University', max_length=100, verbose_name='University')),
                ('study_level', models.CharField(choices=[('first', 'First Level (Bachelor)'), ('second', 'Second Level (Master)'), ('third', 'Third Level (Doctoral)')], max_length=20, verbose_name='Study Level')),
                ('module_type', models.CharField(choices=[('compulsory', 'Compulsory'), ('elective', 'Elective'), ('free_elective', 'Free Elective')], max_length=20, verbose_name='Module Type')),
                ('implementation_form', models.CharField(choices=[('classroom', 'Classroom'), ('distance', 'Distance Learning'), ('mixed', 'Mixed')], max_length=20, verbose_name='Implementation Form')),
                ('semester', models.CharField(max_length=50, verbose_name='Semester')),
                ('language', models.CharField(choices=[('lithuanian', 'Lithuanian'), ('english', 'English'), ('other', 'Other')], max_length=20, verbose_name='Language')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Prerequisites')),
                ('credits', models.IntegerField(verbose_name='Credits')),
                ('total_workload', models.IntegerField(verbose_name='Total Student Workload (hours)')),
                ('contact_hours', models.IntegerField(verbose_name='Contact Hours')),
                ('self_study_hours', models.IntegerField(verbose_name='Self-study Hours')),
                ('general_competencies', models.TextField(verbose_name='General Competencies')),
                ('subject_competencies', models.TextField(verbose_name='Subject-specific Competencies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literature_type', models.CharField(choices=[('required', 'Required Literature'), ('additional', 'Additional Literature')], max_length=20, verbose_name='Literature Type')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('year', models.IntegerField(verbose_name='Publication Year')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('volume_or_issue', models.CharField(blank=True, max_length=100, verbose_name='Volume/Issue')),
                ('publisher_or_url', models.CharField(max_length=300, verbose_name='Publisher/Location or URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature', to='modules.module')),
            ],
            options={
                'ordering': ['literature_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Learning Outcome Description')),
                ('competency_code', models.CharField(blank=True, max_length=20, verbose_name='Competency Code')),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='modules.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100, verbose_name='Assessment Method')),
                ('weight_percentage', models.IntegerField(verbose_name='Weight (%)')),
                ('timing', models.CharField(max_length=100, verbose_name='Assessment Timing')),
                ('criteria', models.TextField(verbose_name='Assessment Criteria')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='modules.module')),
            ],
            options={
                'ordering': ['-weight_percentage'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Topic Title')),
                ('lecture_hours', models.IntegerField(default=0, verbose_name='Lecture Hours')),
                ('consultation_hours', models.IntegerField(default=0, verbose_name='Consultation Hours')),
                ('seminar_hours', models.IntegerField(default=0, verbose_name='Seminar Hours')),
                ('practical_hours', models.IntegerField(default=0, verbose_name='Practical Hours')),
                ('lab_hours', models.IntegerField(default=0, verbose_name='Laboratory Hours')),
                ('consultation_practical_hours', models.IntegerField(default=0, verbose_name='Consultation during Practicals')),
                ('self_study_hours', models.IntegerField(default=0, verbose_name='Self-study Hours')),
                ('assignments', models.TextField(blank=True, verbose_name='Assignments')),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='modules.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
